### ISSUE TITLE
issue to kasia

### ISSUE THREAD

**Issue by petar** [gov4git/roadmap#16]
issue 10000 credits to @KasiaSun

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Monday, 22-Jan-24 22:27:56 UTC` by Gov4Git `dev`

Issued `10000` credits to member @kasiasun.
