### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by ctessum** [gov4git/roadmap#20]
### Your public repo

https://github.com/ctessum/gov4git-identity-public.git

### Your public branch

main

**Comment by petar** [comment]
approve

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Monday, 29-Jan-24 18:00:37 UTC` by Gov4Git `dev`

@ctessum was added to the community.
