### ISSUE TITLE
issue to matching fund

### ISSUE THREAD

**Issue by petar** [gov4git/roadmap#29]
give 1000 credits to matching fund

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Wednesday, 07-Feb-24 02:23:35 UTC` by Gov4Git `dev`

Transferred `1000` credits from member @petar to the matching fund.
