### ISSUE TITLE
issue credits to @petar

### ISSUE THREAD

**Issue by petar** [gov4git/roadmap#4]
issue 10000 credits to @petar

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Friday, 19-Jan-24 22:59:46 UTC` by Gov4Git `dev`

Issued `10000` credits to member @petar.
