### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by shreyjain13** [gov4git/roadmap#5]
### Your public repo

https://github.com/shreyjain13/gov4git-identity-public.git

### Your public branch

main

**Comment by petar** [comment]
approve

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Friday, 19-Jan-24 23:11:02 UTC` by Gov4Git `dev`

@shreyjain13 was added to the community.
